### ISSUE TITLE
Juntar forças !!

### ISSUE THREAD

**Issue by bjverde** [andre-gasparin/VSCode-Adianti-Snippets#1]
Oi André !!

Achei muito bom o seu projeto !! Porém nas pesquisas que fiz achei outro projeto um pouco mais evoluido. O que acha de juntar o seu projeto com o  delphicleancode.

* https://github.com/delphicleancode/AdiantiPHPVsCodeSnippets
* https://medium.com/@carloseduardo_77433/ambiente-de-desenvolvimento-php-com-vscode-e-adianti-framework-5e810c514e22
* https://medium.com/@carloseduardo_77433/criando-code-snippets-de-php-adianti-framework-para-vscode-c571b0b3e7aa
* 

Quero ajudar tambem !! Assim poderá ter um esquema bem legal para o VsCode !!!

**Comment by andre-gasparin** [comment]
Opa @bjverde, se for possível você começar a contribuir nesse repositório, pois essa semana, ou na próxima já vou disponibilizar esse snippet em um plugin nativo do VSCODE!

Em relação ao projeto, obviamente esse possui mais snippets, é só comparar o numero de linhas (1178) para o outro (284), a diferença é que não foi feito descrição e outros adicionais justamente a espera do plugin!

Ficarei feliz com sua contribuição caso queira se juntar a mim nesse projeto, porem se ainda considerar o outro mais viável pra você, quero que fique a vontade, afinal é tudo NOSSO(OPENSOURCE)!  e todas as fontes são válidas!

**Comment by andre-gasparin** [comment]
Eu tinha esquecido de atualizar, atualmente 1524 linhas.

E uma última coisa, quero que fique a vontade também para copiar as funções que preferir e utilizar em outro repositório.
